/* Autogenerated by png2wx.pl on Sat Feb 11 18:37:51 2017 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_AISmaker;
extern wxBitmap *_img_AISmaker_pi;

#endif /* ICONS_H */
